### ISSUE TITLE
💚 ユニットテストを導入する

### ISSUE THREAD

**Issue by tora-muscle** [k-saito-en/1weekPDCA#13]
## 🎫 関連課題
親課題
- #14 

## ✨ 実現したいこと

▼ what?・why?
- [x] `今までの実装分のユニットテストを書く`
  親課題開始時点で実装されているユニットに対して`XCtest`でユニットテストを書くことで GitHub Actions での自動テストが走るようにする。

- [x] `こまめにテストコードを書く習慣をつける`
  細かい粒度でテストコードを更新、テストすることで 「後になって修正祭りで予想外に開発コストがかかりました」 なんてことを防ぎたい。

## 🚩 やらないこと
- `システムテストの導入`
  一時開発終盤に必要に応じて導入

## 🔀 達成条件
- ひとまずはGitHub Actions で自動テストが走るようになればOK！

## 👀 備考

▼ 参考文献
- https://zenn.dev/usk2000/articles/9e3861e76894b7

▼ メモ
- 負荷試験・結合試験の実施の必要は？　▶︎  今月中に調べる

**Comment by tora-muscle** [comment]
### 🗒 macOSアップデート ▶︎ Ruby の編集権限剥奪で`pod update`できなかった

▼ エラー詳細
```bash
/Library/Ruby/Site/2.6.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.6.0/rubygems.rb:284:in `activate_bin_path'
	from /usr/local/bin/pod:23:in `<main>'
```

▼ 原因
- OSアップデートをした段階でsystemのRubyを使うように設定されてしまっており、`pod`コマンド使用時に編集権限がないと怒られていた

▼ 対処法
- gem を全てアンインストールし、インストールし直し、パスを設定し直した

▼ 参考文献
- https://exgyaruo.com/programming/programming-other/cant-find-gem-cocoapods


死のうかと思うくらい焦ったし、修正に時間かかった。。。

**Comment by tora-muscle** [comment]
### 🗒 ViewInspector で書いたテストが BuildFailed していた件

![スクリーンショット 2023-02-23 12 32 24](https://user-images.githubusercontent.com/111550856/220815713-b4f490bc-a8a9-4b56-b5ea-5054afb69909.png)


▼ 原因
- プロジェクトの Package Dependences に ViewInspector を追加しておらず、テストターゲットに ViewInspector が認識されていなかったのでビルドに失敗していた

▼ 対処法
- CocoaPods ではなく、`.xcodeproj`の Package Dependences で ViewInspector を追加、 TARGETS をテストターゲットに指定

▼ 参考文献
- https://www.kodeco.com/30227776-swiftui-testing-with-viewinspector-for-ios

パッケージ管理は全部愚直に CocoaPods で行えばいいわけじゃないのね。。。

**Comment by tora-muscle** [comment]
### 🗒 ViewInspector が優秀すぎた件

**▼ What?**
- ViewInspectorとは、SwiftUIでビューをテストするためのライブラリ。このライブラリには、ざっと以下のような機能がある
   - View の検査と変更
   - View の階層構造の分析
   - View のプロパティの検査

**▼ Why?**
- swiftUI では公式のテストAPIが存在しないらしく、ユニットテストを書くにはサードパーティ製APIが必要
- Xcodeの統合テスト機能はあるが、UITestのように重くなりがちである
- ViewInspectorを使用することで、より柔軟なビューテストを行うことができ、テストのスピードと信頼性が向上する

**▼ When?**
- View のテストを自動化する必要がある場合。
- View の動作を確認したい場合。
- View の構造を理解したい場合。

他にも優秀そうなライブラリはあるが、シンプルに書ける ViewInspector は初学者にはわかりやすかった🙌

**▼ 他のライブラリ抜粋**

- `XCTest`: https://developer.apple.com/documentation/xctest
   Appleが提供するSwift言語用のテストフレームワーク。UIテスト、パフォーマンステスト、統合テスト、単体テストをサポートする。

- `SnapshotTesting`: https://github.com/pointfreeco/swift-snapshot-testing
   ビューのスナップショットテストを行うことができるライブラリ。スナップショットと現在のビューを比較することで、ビューの変更を検出できる。

- `Quick/Nimble` : https://github.com/Quick/Quick
   BDD（Behavior-Driven Development）スタイルのテストフレームワーク。構文が簡潔で、クリーンなテストコードを書くことができる。

- `Cuckoo` : https://github.com/Brightify/Cuckoo
   モックライブラリ。テスト中に他のオブジェクトをシミュレートすることができ、依存関係の解決やテストの効率化を図ることができる。[参考サイト: Cuckoo - GitHub](https://github.com/Brightify/Cuckoo)

- `SwiftUIX` : https://github.com/SwiftUIX/SwiftUIX
   SwiftUIのための拡張ライブラリ。より多くのビューやモディファイアを提供することで、より高度なUIを実現することができる。

- `FBSnapshotTestCase` : https://github.com/facebook/ios-snapshot-test-case
   SnapShotTestingと同様に、ビューのスナップショットテストを行うことができるライブラリ。

**Comment by tora-muscle** [comment]
### 🗒 実装、調べていて感じたテストコードの意義

**▼ Why?**
- `品質保証`
   アプリケーションの品質を保証することができる。また、テストを実行することで、不具合やエラーを発見し、修正することが可能に。

- `リグレッションテスト`
   修正や機能追加などの変更が既存の機能に影響を与えないかを確認することができる。これにより、バグを未然に防ぐ効果がある。

- `ドキュメンテーション`
   コードの意図を明確にすることができる。また、コードの変更があった場合にも、テストコードを通じてコードの動作を確認することができる。

- `個人的な感想`
   ソースの内容を細かに理解していないとテストが書けないので、コードの内容の再確認、深い理解につながる
   - あとは単純に ViewInspector が直感的にテストを書けるので テスト駆動開発（Test-Driven Development: TDD）の際に威力を発揮しそう？
   - 例 : 考えれば当然だが、画面操作の情報を文章で表現できることには感動した👏
   
```swift
func testDeleteTask() throws {
            
        // task を 3 回追加
        for _ in 0 ... 3 {
            taskCardManager.appendTask()
        }
        
        // task カードを右にドラッグした際のジェスチャー情報をスタブ化
        let dummyValue = DragGesture.Value(
            time: Date().addingTimeInterval(-0.5),
            location: .init(x: 20.0, y: 0),
            startLocation: .zero,
            velocity: .zero
        )

        taskCardManager.deleteTask(index: 0, value: dummyValue)
        
        let taskCardView = TaskCardListView().environmentObject(taskCardManager)
        let taskCards = try taskCardView.inspect().forEach(0)
        
        XCTAssertEqual(taskCards.count, taskCardManager.taskCardData.count)
    }
```

▼ 参考文献
- テストコードの意義について
   - https://app.codegrid.net/entry/test-importance-1
   - https://blog.codecamp.jp/test_code_advantages

- ViewInspector
   - https://github.com/nalexn/ViewInspector/blob/0.9.6/guide.md
   - https://www.kodeco.com/30227776-swiftui-testing-with-viewinspector-for-ios

- TDD とは
   - https://www.qbook.jp/column/20181009_713.html

**Comment by tora-muscle** [comment]
### 💢 またまた ruby の実行ファイルが見つからないよエラー発生

**▼ エラー詳細**
```bash
/Library/Ruby/Site/2.6.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.6.0/rubygems.rb:284:in `activate_bin_path'
	from /usr/local/bin/pod:23:in `<main>'
```

**▼ 原因**
- `rbenv global`で`ver.3.2.1`を使うように設定していたが、`Ruby ver.3.2.1`のディレクトリ`usr/local/bin`に cocoapodsが存在せず、「実行ファイルがない」と怒られていたようだ。。。
- また、テストコードを新規に書いた際、Build Target も編集していたので、`podfile`に記載されている Build Target
が存在しない とも怒られたので修正。

**▼ 対処法**
- `sudo gem install cocoapods -n/usr/local/bin`で cocoapods をインストール
- `podfile`の BuildTarget を修正

**▼ 参考文献**
- https://terakoya.sejuku.net/question/detail/39

なんかまた同じエラーが発生しそう。。。🥶
